"""reombrar refresh_token_expiration a refresh_token_expiracion

Revision ID: 0d963f111500
Revises: 99219574328e
Create Date: 2026-07-13 16:44:53.821702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0d963f111500'
down_revision: Union[str, Sequence[str], None] = '99219574328e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Usuarios', sa.Column('refresh_token_expiracion', sa.DateTime(), nullable=True))
    op.drop_column('Usuarios', 'refresh_token_expiration')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Usuarios', sa.Column('refresh_token_expiration', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('Usuarios', 'refresh_token_expiracion')
    # ### end Alembic commands ###
