"""Agregar tabla conceptos y moodificacion de factura

Revision ID: 14c79837b572
Revises: d4946b0ff474
Create Date: 2026-07-17 19:20:07.435020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14c79837b572'
down_revision: Union[str, Sequence[str], None] = 'd4946b0ff474'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Conceptos',
    sa.Column('id_concepto', sa.Integer(), nullable=False),
    sa.Column('id_factura', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=False),
    sa.Column('cantidad', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('unidad', sa.String(), nullable=True),
    sa.Column('precio_unitario', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('importe', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['id_factura'], ['Facturas.id_factura'], ),
    sa.PrimaryKeyConstraint('id_concepto')
    )
    op.create_index(op.f('ix_Conceptos_id_concepto'), 'Conceptos', ['id_concepto'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Conceptos_id_concepto'), table_name='Conceptos')
    op.drop_table('Conceptos')
    # ### end Alembic commands ###
