"""modificacion tabla facturas

Revision ID: 32534667a350
Revises: 14c79837b572
Create Date: 2026-07-20 14:35:16.371829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32534667a350'
down_revision: Union[str, Sequence[str], None] = '14c79837b572'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Facturas', 'cantidad')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Facturas', sa.Column('cantidad', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
