"""origen_y_tc_fuente

Revision ID: 3c91f3e119df
Revises: 4cf7416a8eff
Create Date: 2026-08-29 23:04:37.271808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c91f3e119df'
down_revision: Union[str, Sequence[str], None] = '4cf7416a8eff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Facturas', sa.Column('origen', sa.String(length=20), server_default='gmail', nullable=False))
    op.add_column('Facturas', sa.Column('tipo_cambio_fuente', sa.String(length=20), nullable=True))
    op.add_column('ordenes_compra', sa.Column('origen', sa.String(length=20), server_default='gmail', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ordenes_compra', 'origen')
    op.drop_column('Facturas', 'tipo_cambio_fuente')
    op.drop_column('Facturas', 'origen')
    # ### end Alembic commands ###
