"""message_id_y_nullable_facturas

Revision ID: 4a79709ef567
Revises: fe748321bb59
Create Date: 2026-08-07 18:40:28.664617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a79709ef567'
down_revision: Union[str, Sequence[str], None] = 'fe748321bb59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Facturas', sa.Column('message_id', sa.String(), nullable=True))
    op.alter_column('Facturas', 'folio_interno',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_unique_constraint(None, 'Facturas', ['message_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Facturas', type_='unique')
    op.alter_column('Facturas', 'folio_interno',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('Facturas', 'message_id')
    # ### end Alembic commands ###
