"""agregar_clientes

Revision ID: 4cf7416a8eff
Revises: 8eca2c0018dd
Create Date: 2026-08-28 19:23:42.222356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cf7416a8eff'
down_revision: Union[str, Sequence[str], None] = '8eca2c0018dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Facturas', sa.Column('cliente', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Facturas', 'cliente')
    # ### end Alembic commands ###
