"""Agregar tabla cliente

Revision ID: 8eca2c0018dd
Revises: bce9ea1ab852
Create Date: 2026-08-28 18:24:18.209421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8eca2c0018dd'
down_revision: Union[str, Sequence[str], None] = 'bce9ea1ab852'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rfc', sa.String(length=13), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('dias_plazo_pago', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Clientes_id'), 'Clientes', ['id'], unique=False)
    op.create_index(op.f('ix_Clientes_rfc'), 'Clientes', ['rfc'], unique=True)
    op.create_table('ClientesCorreos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('valor', sa.String(length=255), nullable=False),
    sa.Column('es_dominio', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_cliente'], ['Clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ClientesCorreos_id'), 'ClientesCorreos', ['id'], unique=False)
    op.create_index(op.f('ix_ClientesCorreos_id_cliente'), 'ClientesCorreos', ['id_cliente'], unique=False)
    op.create_index(op.f('ix_ClientesCorreos_valor'), 'ClientesCorreos', ['valor'], unique=True)
    op.drop_index(op.f('ix_cp_message_id'), table_name='ComplementosPago')
    op.create_unique_constraint(None, 'ComplementosPago', ['message_id'])
    op.add_column('Facturas', sa.Column('id_cliente', sa.Integer(), nullable=True))
    op.add_column('Facturas', sa.Column('dias_plazo_pago_aplicado', sa.Integer(), nullable=True))
    op.alter_column('Facturas', 'moneda',
               existing_type=sa.VARCHAR(length=3),
               nullable=False,
               existing_server_default=sa.text("'MXN'::character varying"))
    op.drop_index(op.f('ix_facturas_fecha'), table_name='Facturas')
    op.drop_index(op.f('ix_facturas_message_id'), table_name='Facturas')
    op.create_index(op.f('ix_Facturas_id_cliente'), 'Facturas', ['id_cliente'], unique=False)
    op.create_unique_constraint(None, 'Facturas', ['message_id'])
    op.create_foreign_key(None, 'Facturas', 'Clientes', ['id_cliente'], ['id'])
    op.drop_column('Facturas', 'cliente')
    op.add_column('ordenes_compra', sa.Column('id_cliente', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_ordenes_compra_id_cliente'), 'ordenes_compra', ['id_cliente'], unique=False)
    op.create_foreign_key(None, 'ordenes_compra', 'Clientes', ['id_cliente'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ordenes_compra', type_='foreignkey')
    op.drop_index(op.f('ix_ordenes_compra_id_cliente'), table_name='ordenes_compra')
    op.drop_column('ordenes_compra', 'id_cliente')
    op.add_column('Facturas', sa.Column('cliente', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Facturas', type_='foreignkey')
    op.drop_constraint(None, 'Facturas', type_='unique')
    op.drop_index(op.f('ix_Facturas_id_cliente'), table_name='Facturas')
    op.create_index(op.f('ix_facturas_message_id'), 'Facturas', ['message_id'], unique=False)
    op.create_index(op.f('ix_facturas_fecha'), 'Facturas', ['fecha'], unique=False)
    op.alter_column('Facturas', 'moneda',
               existing_type=sa.VARCHAR(length=3),
               nullable=True,
               existing_server_default=sa.text("'MXN'::character varying"))
    op.drop_column('Facturas', 'dias_plazo_pago_aplicado')
    op.drop_column('Facturas', 'id_cliente')
    op.drop_constraint(None, 'ComplementosPago', type_='unique')
    op.create_index(op.f('ix_cp_message_id'), 'ComplementosPago', ['message_id'], unique=False)
    op.drop_index(op.f('ix_ClientesCorreos_valor'), table_name='ClientesCorreos')
    op.drop_index(op.f('ix_ClientesCorreos_id_cliente'), table_name='ClientesCorreos')
    op.drop_index(op.f('ix_ClientesCorreos_id'), table_name='ClientesCorreos')
    op.drop_table('ClientesCorreos')
    op.drop_index(op.f('ix_Clientes_rfc'), table_name='Clientes')
    op.drop_index(op.f('ix_Clientes_id'), table_name='Clientes')
    op.drop_table('Clientes')
    # ### end Alembic commands ###
