"""reombrar refresh_token_expiration a refresh_token_expiracion

Revision ID: 99219574328e
Revises: d6cdc6e76452
Create Date: 2026-07-13 16:33:05.711553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99219574328e'
down_revision: Union[str, Sequence[str], None] = 'd6cdc6e76452'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
