"""hash_archivo_dedupe

Revision ID: b0986b7c063a
Revises: 4a79709ef567
Create Date: 2026-08-12 19:51:17.932787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0986b7c063a'
down_revision: Union[str, Sequence[str], None] = '4a79709ef567'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ComplementosPago', sa.Column('hash_archivo', sa.String(length=64), nullable=True))
    op.create_unique_constraint(None, 'ComplementosPago', ['hash_archivo'])
    op.add_column('ordenes_compra', sa.Column('hash_archivo', sa.String(length=64), nullable=True))
    op.create_unique_constraint(None, 'ordenes_compra', ['hash_archivo'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ordenes_compra', type_='unique')
    op.drop_column('ordenes_compra', 'hash_archivo')
    op.drop_constraint(None, 'ComplementosPago', type_='unique')
    op.drop_column('ComplementosPago', 'hash_archivo')
    # ### end Alembic commands ###
