"""modificar campos de factura y agregar autoincrementos

Revision ID: d4946b0ff474
Revises: d9e84de84ab7
Create Date: 2026-07-16 18:58:47.753604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4946b0ff474'
down_revision: Union[str, Sequence[str], None] = 'd9e84de84ab7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Facturas', sa.Column('folio_fiscal', sa.String(), nullable=False))
    op.add_column('Facturas', sa.Column('cantidad', sa.Integer(), nullable=False))
    op.add_column('Facturas', sa.Column('folio_interno', sa.String(), nullable=False))
    op.add_column('Facturas', sa.Column('orden_compra', sa.String(), nullable=False))
    op.add_column('Facturas', sa.Column('tipo_cambio', sa.String(), nullable=True))
    op.add_column('Facturas', sa.Column('subtotal', sa.DECIMAL(precision=10, scale=2), nullable=True))
    op.add_column('Facturas', sa.Column('iva', sa.DECIMAL(precision=10, scale=2), nullable=True))
    op.add_column('Facturas', sa.Column('total', sa.DECIMAL(precision=10, scale=2), nullable=True))
    op.add_column('Facturas', sa.Column('pdf_factura', sa.LargeBinary(), nullable=True))
    op.add_column('Facturas', sa.Column('xml_factura', sa.LargeBinary(), nullable=True))
    op.add_column('Facturas', sa.Column('orden_compra_archivo', sa.LargeBinary(), nullable=True))
    op.drop_column('Facturas', 'folio')
    op.drop_column('Facturas', 'banco')
    op.drop_column('Facturas', 'monto')
    op.drop_column('Facturas', 'descripcion')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Facturas', sa.Column('descripcion', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('Facturas', sa.Column('monto', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.add_column('Facturas', sa.Column('banco', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('Facturas', sa.Column('folio', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('Facturas', 'orden_compra_archivo')
    op.drop_column('Facturas', 'xml_factura')
    op.drop_column('Facturas', 'pdf_factura')
    op.drop_column('Facturas', 'total')
    op.drop_column('Facturas', 'iva')
    op.drop_column('Facturas', 'subtotal')
    op.drop_column('Facturas', 'tipo_cambio')
    op.drop_column('Facturas', 'orden_compra')
    op.drop_column('Facturas', 'folio_interno')
    op.drop_column('Facturas', 'cantidad')
    op.drop_column('Facturas', 'folio_fiscal')
    # ### end Alembic commands ###
