"""agregar refresh a los usuarios

Revision ID: d6cdc6e76452
Revises: db5c71a5d89d
Create Date: 2026-07-13 16:13:40.740959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6cdc6e76452'
down_revision: Union[str, Sequence[str], None] = 'db5c71a5d89d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Usuarios', sa.Column('refresh_token', sa.String(), nullable=True))
    op.add_column('Usuarios', sa.Column('refresh_token_expiration', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Usuarios', 'refresh_token_expiration')
    op.drop_column('Usuarios', 'refresh_token')
    # ### end Alembic commands ###
