"""crear tabla configuracion_sistema toma2

Revision ID: d9e84de84ab7
Revises: 0d963f111500
Create Date: 2026-07-14 22:24:19.528420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9e84de84ab7'
down_revision: Union[str, Sequence[str], None] = '0d963f111500'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracion_sistema',
    sa.Column('id_CS', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('clave', sa.String(), nullable=False),
    sa.Column('valor', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id_CS'),
    sa.UniqueConstraint('clave')
    )
    op.create_index(op.f('ix_configuracion_sistema_id_CS'), 'configuracion_sistema', ['id_CS'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_configuracion_sistema_id_CS'), table_name='configuracion_sistema')
    op.drop_table('configuracion_sistema')
    # ### end Alembic commands ###
