"""Modificacion-Factura

Revision ID: fb379c199137
Revises: b0986b7c063a
Create Date: 2026-08-17 18:10:28.519194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb379c199137'
down_revision: Union[str, Sequence[str], None] = 'b0986b7c063a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Facturas', sa.Column('fecha_validacion', sa.Date(), nullable=True))
    op.add_column('Facturas', sa.Column('moneda', sa.String(length=3), server_default='MXN', nullable=True))
    op.alter_column('Facturas', 'tipo_cambio',
               existing_type=sa.VARCHAR(),
               type_=sa.DECIMAL(precision=18, scale=6),
               existing_nullable=True)
    op.create_index(op.f('ix_Facturas_fecha'), 'Facturas', ['fecha'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Facturas_fecha'), table_name='Facturas')
    op.alter_column('Facturas', 'tipo_cambio',
               existing_type=sa.DECIMAL(precision=18, scale=6),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('Facturas', 'moneda')
    op.drop_column('Facturas', 'fecha_validacion')
    # ### end Alembic commands ###
