"""redesign_flujo_oc_factura_cp

Revision ID: fe748321bb59
Revises: 37a134073a8a
Create Date: 2026-08-06 16:56:33.958789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe748321bb59'
down_revision: Union[str, Sequence[str], None] = '37a134073a8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ComplementosPago',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid_cp', sa.String(), nullable=False),
    sa.Column('folio', sa.String(), nullable=True),
    sa.Column('fecha_pago', sa.DateTime(), nullable=False),
    sa.Column('moneda', sa.String(length=10), nullable=True),
    sa.Column('tipo_cambio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('monto', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('forma_pago', sa.String(length=50), nullable=True),
    sa.Column('archivo_xml', sa.LargeBinary(), nullable=True),
    sa.Column('archivo_pdf', sa.LargeBinary(), nullable=True),
    sa.Column('message_id', sa.String(), nullable=False),
    sa.Column('fecha_recepcion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id'),
    sa.UniqueConstraint('uuid_cp')
    )
    op.create_index(op.f('ix_ComplementosPago_id'), 'ComplementosPago', ['id'], unique=False)
    op.create_table('CorreosFallidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.String(), nullable=False),
    sa.Column('error', sa.String(), nullable=False),
    sa.Column('fecha_fallo', sa.DateTime(), nullable=True),
    sa.Column('resuelto', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_CorreosFallidos_id'), 'CorreosFallidos', ['id'], unique=False)
    op.create_table('CorreosProcesados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.String(), nullable=False),
    sa.Column('tipo_correo', sa.String(length=30), nullable=True),
    sa.Column('fecha_procesado', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id')
    )
    op.create_index(op.f('ix_CorreosProcesados_id'), 'CorreosProcesados', ['id'], unique=False)
    op.create_table('ordenes_compra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_oc', sa.String(), nullable=True),
    sa.Column('numero_oc_detectado', sa.String(), nullable=True),
    sa.Column('archivo', sa.LargeBinary(), nullable=True),
    sa.Column('nombre_archivo', sa.String(), nullable=True),
    sa.Column('message_id', sa.String(), nullable=False),
    sa.Column('fecha_recepcion', sa.DateTime(), nullable=True),
    sa.Column('capturada_por', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['capturada_por'], ['Usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id')
    )
    op.create_index(op.f('ix_ordenes_compra_id'), 'ordenes_compra', ['id'], unique=False)
    op.create_table('cp_documentos_relacionados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_complemento', sa.Integer(), nullable=False),
    sa.Column('uuid_documento', sa.String(), nullable=False),
    sa.Column('id_factura', sa.Integer(), nullable=True),
    sa.Column('num_parcialidad', sa.Integer(), nullable=True),
    sa.Column('imp_pagado', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('imp_saldo_insoluto', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['id_complemento'], ['ComplementosPago.id'], ),
    sa.ForeignKeyConstraint(['id_factura'], ['Facturas.id_factura'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cp_documentos_relacionados_id'), 'cp_documentos_relacionados', ['id'], unique=False)
    op.add_column('Facturas', sa.Column('numero_oc', sa.String(), nullable=True))
    op.add_column('Facturas', sa.Column('fecha_liquidacion', sa.Date(), nullable=True))
    op.add_column('Facturas', sa.Column('id_orden_compra', sa.Integer(), nullable=True))
    op.add_column('Facturas', sa.Column('numero_oc_detectado', sa.String(), nullable=True))
    op.create_foreign_key(None, 'Facturas', 'ordenes_compra', ['id_orden_compra'], ['id'])
    op.drop_column('Facturas', 'orden_compra')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Facturas', sa.Column('orden_compra', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'Facturas', type_='foreignkey')
    op.drop_column('Facturas', 'numero_oc_detectado')
    op.drop_column('Facturas', 'id_orden_compra')
    op.drop_column('Facturas', 'fecha_liquidacion')
    op.drop_column('Facturas', 'numero_oc')
    op.drop_index(op.f('ix_cp_documentos_relacionados_id'), table_name='cp_documentos_relacionados')
    op.drop_table('cp_documentos_relacionados')
    op.drop_index(op.f('ix_ordenes_compra_id'), table_name='ordenes_compra')
    op.drop_table('ordenes_compra')
    op.drop_index(op.f('ix_CorreosProcesados_id'), table_name='CorreosProcesados')
    op.drop_table('CorreosProcesados')
    op.drop_index(op.f('ix_CorreosFallidos_id'), table_name='CorreosFallidos')
    op.drop_table('CorreosFallidos')
    op.drop_index(op.f('ix_ComplementosPago_id'), table_name='ComplementosPago')
    op.drop_table('ComplementosPago')
    # ### end Alembic commands ###
